In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
lista = [1,2,5,8,1,42,6,8,92]
lista2 = [5,4,6,9,45,7,3,47,1]

In [4]:
lista

[1, 2, 5, 8, 1, 42, 6, 8, 92]

In [5]:
a = np.array(lista)
a

array([ 1,  2,  5,  8,  1, 42,  6,  8, 92])

In [9]:
b = np.array([lista, lista2], dtype = float)
b

array([[ 1.,  2.,  5.,  8.,  1., 42.,  6.,  8., 92.],
       [ 5.,  4.,  6.,  9., 45.,  7.,  3., 47.,  1.]])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [14]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [15]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [16]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [17]:
np.linspace(1,10,19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [19]:
aa = np.linspace(1,10,19, dtype = float)

In [20]:
len(aa)

19

In [21]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [23]:
np.full((3,3), np.arange(1,10).reshape(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.random((4,2))

array([[0.78383211, 0.34381484],
       [0.85125865, 0.66827185],
       [0.12719779, 0.1890741 ],
       [0.45655339, 0.52145529]])

In [42]:
a = np.random.random(10)

In [ ]:
"""
Utility functions
    -------------------- ---------------------------------------------------------
    random               Uniformly distributed floats over ``[0, 1)``
    bytes                Uniformly distributed random bytes.
    permutation          Randomly permute a sequence / generate a random sequence.
    shuffle              Randomly permute a sequence in place.
    choice               Random sample from 1-D array.

"""  

In [60]:
lista

[1, 2, 5, 8, 1, 42, 6, 8, 92]

In [59]:
np.random.permutation(lista)

array([92, 42,  8,  8,  2,  1,  1,  6,  5])

In [47]:
np.random.permutation(10)

array([4, 8, 5, 3, 2, 9, 6, 0, 7, 1], dtype=int32)

In [51]:
lista2

[9, 1, 6, 45, 3, 4, 7, 47, 5]

In [52]:
np.random.shuffle(lista2)

In [53]:
lista2

[1, 6, 3, 9, 5, 47, 7, 45, 4]

In [54]:
np.random.choice(lista2)

np.int64(47)

In [61]:
np.full((2,2), 5)

array([[5, 5],
       [5, 5]])

In [62]:
a.shape

(10,)

In [63]:
len(a)

10

In [64]:
b.shape

(2, 9)

In [65]:
b.ndim

2

In [66]:
b.size

18

In [67]:
len(b)

2

In [68]:
b

array([[ 1.,  2.,  5.,  8.,  1., 42.,  6.,  8., 92.],
       [ 5.,  4.,  6.,  9., 45.,  7.,  3., 47.,  1.]])

In [69]:
b.size

18

In [70]:
b.dtype

dtype('float64')

In [71]:
b.dtype.name

'float64'

In [72]:
b.astype(int)

array([[ 1,  2,  5,  8,  1, 42,  6,  8, 92],
       [ 5,  4,  6,  9, 45,  7,  3, 47,  1]])

In [73]:
b.dtype

dtype('float64')

In [74]:
c = np.random.randint(18, size = (2,9))

In [75]:
c

array([[ 2, 16,  4,  3,  5,  6, 12,  3,  6],
       [12,  3, 16,  9, 14,  8, 16, 11,  6]], dtype=int32)

In [76]:
d = b + c
d

array([[ 3., 18.,  9., 11.,  6., 48., 18., 11., 98.],
       [17.,  7., 22., 18., 59., 15., 19., 58.,  7.]])

In [77]:
d.astype(int)

array([[ 3, 18,  9, 11,  6, 48, 18, 11, 98],
       [17,  7, 22, 18, 59, 15, 19, 58,  7]])

In [78]:
d

array([[ 3., 18.,  9., 11.,  6., 48., 18., 11., 98.],
       [17.,  7., 22., 18., 59., 15., 19., 58.,  7.]])

In [80]:
d = d.astype(int)

In [81]:
d

array([[ 3, 18,  9, 11,  6, 48, 18, 11, 98],
       [17,  7, 22, 18, 59, 15, 19, 58,  7]])

In [82]:
np.add(b,c)

array([[ 3., 18.,  9., 11.,  6., 48., 18., 11., 98.],
       [17.,  7., 22., 18., 59., 15., 19., 58.,  7.]])

In [83]:
np.subtract(b,c)

array([[ -1., -14.,   1.,   5.,  -4.,  36.,  -6.,   5.,  86.],
       [ -7.,   1., -10.,   0.,  31.,  -1., -13.,  36.,  -5.]])

In [84]:
np.divide(b,c)

array([[ 0.5       ,  0.125     ,  1.25      ,  2.66666667,  0.2       ,
         7.        ,  0.5       ,  2.66666667, 15.33333333],
       [ 0.41666667,  1.33333333,  0.375     ,  1.        ,  3.21428571,
         0.875     ,  0.1875    ,  4.27272727,  0.16666667]])

In [91]:
np.divmod(b,c)[1]

array([[1., 2., 1., 2., 1., 0., 6., 2., 2.],
       [5., 1., 6., 0., 3., 7., 3., 3., 1.]])

In [86]:
b

array([[ 1.,  2.,  5.,  8.,  1., 42.,  6.,  8., 92.],
       [ 5.,  4.,  6.,  9., 45.,  7.,  3., 47.,  1.]])

In [87]:
c

array([[ 2, 16,  4,  3,  5,  6, 12,  3,  6],
       [12,  3, 16,  9, 14,  8, 16, 11,  6]], dtype=int32)

In [92]:
np.multiply(b,c)

array([[  2.,  32.,  20.,  24.,   5., 252.,  72.,  24., 552.],
       [ 60.,  12.,  96.,  81., 630.,  56.,  48., 517.,   6.]])

In [93]:
np.exp(b)

array([[2.71828183e+00, 7.38905610e+00, 1.48413159e+02, 2.98095799e+03,
        2.71828183e+00, 1.73927494e+18, 4.03428793e+02, 2.98095799e+03,
        9.01762841e+39],
       [1.48413159e+02, 5.45981500e+01, 4.03428793e+02, 8.10308393e+03,
        3.49342711e+19, 1.09663316e+03, 2.00855369e+01, 2.58131289e+20,
        2.71828183e+00]])

In [94]:
np.exp(1)

np.float64(2.718281828459045)

In [96]:
np.sqrt(b).round(2)

array([[1.  , 1.41, 2.24, 2.83, 1.  , 6.48, 2.45, 2.83, 9.59],
       [2.24, 2.  , 2.45, 3.  , 6.71, 2.65, 1.73, 6.86, 1.  ]])

In [97]:
np.log(1000)

np.float64(6.907755278982137)

In [98]:
aaa = np.random.randint(9, size = (3,3))
aaa

array([[2, 0, 0],
       [7, 7, 0],
       [2, 6, 3]], dtype=int32)

In [101]:
ind = np.eye(3)
ind

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
np.dot(aaa, ind)

array([[2., 0., 0.],
       [7., 7., 0.],
       [2., 6., 3.]])

In [105]:
np.dot(np.arange(6).reshape(2,3), np.arange(10,16).reshape(3,2)) 

array([[ 40,  43],
       [148, 160]])

In [106]:
b > c

array([[False, False,  True,  True, False,  True, False,  True,  True],
       [False,  True, False, False,  True, False, False,  True, False]])

In [107]:
b.sum()

np.float64(292.0)

In [108]:
b

array([[ 1.,  2.,  5.,  8.,  1., 42.,  6.,  8., 92.],
       [ 5.,  4.,  6.,  9., 45.,  7.,  3., 47.,  1.]])

In [109]:
b.min()

np.float64(1.0)

In [110]:
b.min(axis=1)

array([1., 1.])

In [111]:
b.min(axis=0)

array([1., 2., 5., 8., 1., 7., 3., 8., 1.])

In [112]:
b.max(axis=1)

array([92., 47.])

In [113]:
b.max(axis=0)

array([ 5.,  4.,  6.,  9., 45., 42.,  6., 47., 92.])

In [114]:
b.cumsum()

array([  1.,   3.,   8.,  16.,  17.,  59.,  65.,  73., 165., 170., 174.,
       180., 189., 234., 241., 244., 291., 292.])

In [115]:
b.cumsum(axis=0)

array([[ 1.,  2.,  5.,  8.,  1., 42.,  6.,  8., 92.],
       [ 6.,  6., 11., 17., 46., 49.,  9., 55., 93.]])

In [116]:
b.cumsum(axis=1)

array([[  1.,   3.,   8.,  16.,  17.,  59.,  65.,  73., 165.],
       [  5.,   9.,  15.,  24.,  69.,  76.,  79., 126., 127.]])

In [117]:
b.mean(axis=0)

array([ 3. ,  3. ,  5.5,  8.5, 23. , 24.5,  4.5, 27.5, 46.5])

In [118]:
b

array([[ 1.,  2.,  5.,  8.,  1., 42.,  6.,  8., 92.],
       [ 5.,  4.,  6.,  9., 45.,  7.,  3., 47.,  1.]])

In [119]:
b.mean()

np.float64(16.22222222222222)

In [120]:
b.mean(axis=1)

array([18.33333333, 14.11111111])

In [131]:
b

array([[ 1.,  2.,  5.,  8.,  1., 42.,  6.,  8., 92.],
       [ 5.,  4.,  6.,  9., 45.,  7.,  3., 47.,  1.]])

In [134]:
l1 = b[1,]

In [135]:
l2 = b[0,]

In [136]:
np.corrcoef(l1,l2)

array([[ 1.        , -0.31303038],
       [-0.31303038,  1.        ]])

In [121]:
np.corrcoef(b)

array([[ 1.        , -0.31303038],
       [-0.31303038,  1.        ]])

In [127]:
np.corrcoef(np.full((10,2),5))

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [138]:
e = np.arange(5,10)
e

array([5, 6, 7, 8, 9])

In [139]:
f = e.view()
f

array([5, 6, 7, 8, 9])

In [140]:
e[2] = 10
e

array([ 5,  6, 10,  8,  9])

In [141]:
f

array([ 5,  6, 10,  8,  9])

In [142]:
g = e.copy()
g

array([ 5,  6, 10,  8,  9])

In [143]:
e[0] = 14
e

array([14,  6, 10,  8,  9])

In [144]:
f

array([14,  6, 10,  8,  9])

In [145]:
g

array([ 5,  6, 10,  8,  9])

In [146]:
b

array([[ 1.,  2.,  5.,  8.,  1., 42.,  6.,  8., 92.],
       [ 5.,  4.,  6.,  9., 45.,  7.,  3., 47.,  1.]])

In [147]:
b.sort()

In [148]:
b

array([[ 1.,  1.,  2.,  5.,  6.,  8.,  8., 42., 92.],
       [ 1.,  3.,  4.,  5.,  6.,  7.,  9., 45., 47.]])

In [149]:
b.sort(axis=0)

In [150]:
b

array([[ 1.,  1.,  2.,  5.,  6.,  7.,  8., 42., 47.],
       [ 1.,  3.,  4.,  5.,  6.,  8.,  9., 45., 92.]])

In [151]:
c

array([[ 2, 16,  4,  3,  5,  6, 12,  3,  6],
       [12,  3, 16,  9, 14,  8, 16, 11,  6]], dtype=int32)

In [152]:
c2 = c.copy()
c2

array([[ 2, 16,  4,  3,  5,  6, 12,  3,  6],
       [12,  3, 16,  9, 14,  8, 16, 11,  6]], dtype=int32)

In [153]:
c.sort()
c

array([[ 2,  3,  3,  4,  5,  6,  6, 12, 16],
       [ 3,  6,  8,  9, 11, 12, 14, 16, 16]], dtype=int32)

In [154]:
c

array([[ 2,  3,  3,  4,  5,  6,  6, 12, 16],
       [ 3,  6,  8,  9, 11, 12, 14, 16, 16]], dtype=int32)

In [155]:
c2

array([[ 2, 16,  4,  3,  5,  6, 12,  3,  6],
       [12,  3, 16,  9, 14,  8, 16, 11,  6]], dtype=int32)

In [156]:
c2.sort(axis=0)
c2

array([[ 2,  3,  4,  3,  5,  6, 12,  3,  6],
       [12, 16, 16,  9, 14,  8, 16, 11,  6]], dtype=int32)

In [157]:
b

array([[ 1.,  1.,  2.,  5.,  6.,  7.,  8., 42., 47.],
       [ 1.,  3.,  4.,  5.,  6.,  8.,  9., 45., 92.]])

In [158]:
b[1]

array([ 1.,  3.,  4.,  5.,  6.,  8.,  9., 45., 92.])

In [159]:
b[1,1]

np.float64(3.0)

In [160]:
b[0, :3]

array([1., 1., 2.])

In [161]:
b<5

array([[ True,  True,  True, False, False, False, False, False, False],
       [ True,  True,  True, False, False, False, False, False, False]])

In [162]:
b[b<5]

array([1., 1., 2., 1., 3., 4.])

In [163]:
b[:-1]

array([[ 1.,  1.,  2.,  5.,  6.,  7.,  8., 42., 47.]])

In [164]:
b[::-1]

array([[ 1.,  3.,  4.,  5.,  6.,  8.,  9., 45., 92.],
       [ 1.,  1.,  2.,  5.,  6.,  7.,  8., 42., 47.]])

In [165]:
b[[0,0,1,1],[3,-1,0,-1]]

array([ 5., 47.,  1., 92.])

In [166]:
b.T

array([[ 1.,  1.],
       [ 1.,  3.],
       [ 2.,  4.],
       [ 5.,  5.],
       [ 6.,  6.],
       [ 7.,  8.],
       [ 8.,  9.],
       [42., 45.],
       [47., 92.]])

In [167]:
b.transpose()

array([[ 1.,  1.],
       [ 1.,  3.],
       [ 2.,  4.],
       [ 5.,  5.],
       [ 6.,  6.],
       [ 7.,  8.],
       [ 8.,  9.],
       [42., 45.],
       [47., 92.]])

In [171]:
b.reshape(3,6)

array([[ 1.,  1.,  2.,  5.,  6.,  7.],
       [ 8., 42., 47.,  1.,  3.,  4.],
       [ 5.,  6.,  8.,  9., 45., 92.]])

In [169]:
b

array([[ 1.,  1.,  2.,  5.,  6.,  7.,  8., 42., 47.],
       [ 1.,  3.,  4.,  5.,  6.,  8.,  9., 45., 92.]])

In [173]:
b.reshape(3,6, order="F")

array([[ 1.,  3.,  5.,  6.,  8., 45.],
       [ 1.,  2.,  5.,  7.,  9., 47.],
       [ 1.,  4.,  6.,  8., 42., 92.]])

In [175]:
b.ravel()

array([ 1.,  1.,  2.,  5.,  6.,  7.,  8., 42., 47.,  1.,  3.,  4.,  5.,
        6.,  8.,  9., 45., 92.])

In [176]:
b

array([[ 1.,  1.,  2.,  5.,  6.,  7.,  8., 42., 47.],
       [ 1.,  3.,  4.,  5.,  6.,  8.,  9., 45., 92.]])

In [177]:
# inplace. reshape não é inplace
b.resize(3,6)

In [178]:
b

array([[ 1.,  1.,  2.,  5.,  6.,  7.],
       [ 8., 42., 47.,  1.,  3.,  4.],
       [ 5.,  6.,  8.,  9., 45., 92.]])

In [179]:
b.ravel()

array([ 1.,  1.,  2.,  5.,  6.,  7.,  8., 42., 47.,  1.,  3.,  4.,  5.,
        6.,  8.,  9., 45., 92.])